version: "3.4"

services:
  backend:
    image: backend/php8.2-apache:latest
    user: "$USER:${GID}"
    container_name: backend_docker
    working_dir: /var/www/html

    ports:
      - 80:80

    volumes:
      - type: bind
        source: .
        target: /var/www/html
      